# Generated by Django 5.0.7 on 2024-09-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_unidad_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
