# Generated by Django 5.0.7 on 2024-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_inquilino_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoservicio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuotamantenimiento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
