# Generated by Django 5.0.7 on 2024-08-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='area',
        ),
    ]
