# Generated by Django 5.0.7 on 2024-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_unidad_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='coeficiente',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
