# Generated by Django 5.0.7 on 2024-09-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_unidad_coeficiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='pago',
            name='contratoServicio',
        ),
        migrations.RemoveField(
            model_name='cuotamantenimiento',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cuota',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='propiedad',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='propietario',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fecha',
            new_name='fecha_pago',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='año_construcción',
            new_name='Presupuesto',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='numero_pisos',
            new_name='cuota',
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='direccion',
            new_name='nombre_propiedad',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='propiedad',
            new_name='id_propiedad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='nombre_edificio',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='tipo_unidad',
        ),
        migrations.AddField(
            model_name='pago',
            name='id_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propiedad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.unidad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_pago',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios')], default='mantenimiento', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='direccion_propiedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='cedula_inquilino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='nombre_inquilino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='telefono_inquilino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='coeficiente',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='numero_unidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='ContratoServicio',
        ),
        migrations.DeleteModel(
            name='CuotaMantenimiento',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
