# Generated by Django 5.0.7 on 2024-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_usuario_remove_pago_contratoservicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='estado',
            field=models.BooleanField(default=0),
        ),
    ]
